# Generated by Django 2.0.1 on 2018-01-10 21:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('enabled', models.BooleanField()),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='BotGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BotVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('name', models.CharField(max_length=255)),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('deleted', models.BooleanField(default=False)),
                ('bot_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Bot')),
            ],
        ),
        migrations.CreateModel(
            name='SnakeDesign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SnakeDesignFlag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('img', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='SnakeDesignHead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('img', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='SnakeDesignSegment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_id', models.IntegerField()),
                ('color_r', models.IntegerField()),
                ('color_g', models.IntegerField()),
                ('color_b', models.IntegerField()),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.SnakeDesign')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Team')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='snakedesign',
            name='flag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.SnakeDesignFlag'),
        ),
        migrations.AddField(
            model_name='snakedesign',
            name='head',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.SnakeDesignHead'),
        ),
        migrations.AddField(
            model_name='snakedesign',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='botversion',
            name='design',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.SnakeDesign'),
        ),
        migrations.AddField(
            model_name='botgame',
            name='bot_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.BotVersion'),
        ),
        migrations.AddField(
            model_name='botgame',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Team'),
        ),
        migrations.AddField(
            model_name='bot',
            name='design',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.SnakeDesign'),
        ),
        migrations.AddField(
            model_name='bot',
            name='selected_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.BotVersion'),
        ),
        migrations.AddField(
            model_name='bot',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
