# Generated by Django 2.0.1 on 2018-01-20 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snakedesign',
            name='flag',
        ),
        migrations.RemoveField(
            model_name='snakedesign',
            name='head',
        ),
        migrations.RemoveField(
            model_name='snakedesign',
            name='user',
        ),
        migrations.RemoveField(
            model_name='snakedesignsegment',
            name='design',
        ),
        migrations.RemoveField(
            model_name='bot',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='bot',
            name='design',
        ),
        migrations.RemoveField(
            model_name='bot',
            name='enabled',
        ),
        migrations.RemoveField(
            model_name='botversion',
            name='design',
        ),
        migrations.DeleteModel(
            name='SnakeDesign',
        ),
        migrations.DeleteModel(
            name='SnakeDesignFlag',
        ),
        migrations.DeleteModel(
            name='SnakeDesignHead',
        ),
        migrations.DeleteModel(
            name='SnakeDesignSegment',
        ),
    ]
