# Generated by Django 2.0.1 on 2018-01-20 20:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_auto_20180120_2122'),
    ]

    operations = [
        migrations.CreateModel(
            name='Snake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SnakeGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SnakeVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('name', models.CharField(max_length=255)),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('deleted', models.BooleanField(default=False)),
                ('snake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Snake')),
            ],
        ),
        migrations.RemoveField(
            model_name='bot',
            name='selected_version',
        ),
        migrations.RemoveField(
            model_name='bot',
            name='user',
        ),
        migrations.RemoveField(
            model_name='botgame',
            name='bot_version',
        ),
        migrations.RemoveField(
            model_name='botgame',
            name='team',
        ),
        migrations.RemoveField(
            model_name='botversion',
            name='bot_instance',
        ),
        migrations.DeleteModel(
            name='Bot',
        ),
        migrations.DeleteModel(
            name='BotGame',
        ),
        migrations.DeleteModel(
            name='BotVersion',
        ),
        migrations.AddField(
            model_name='snakegame',
            name='snake_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.SnakeVersion'),
        ),
        migrations.AddField(
            model_name='snakegame',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Team'),
        ),
        migrations.AddField(
            model_name='snake',
            name='selected_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='selected_version', to='core.SnakeVersion'),
        ),
        migrations.AddField(
            model_name='snake',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
