# Generated by Django 2.0.1 on 2018-01-20 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180120_2157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snake',
            name='selected_version',
        ),
    ]
