# Generated by Django 2.0.4 on 2018-04-11 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20180330_2245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snake',
            name='name',
        ),
        migrations.AddField(
            model_name='snakeversion',
            name='comment',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
