# Generated by Django 2.0.4 on 2018-04-11 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20180411_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='snakeversion',
            name='version',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
