# Generated by Django 2.0.4 on 2018-04-11 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_snakeversion_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snake',
            name='user',
        ),
        migrations.RemoveField(
            model_name='snakeversion',
            name='snake',
        ),
        migrations.DeleteModel(
            name='Snake',
        ),
    ]
