# Generated by Django 2.0.4 on 2018-04-11 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_snakeversion_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='snakeversion',
            name='prev_version',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
