# Generated by Django 2.0.4 on 2018-04-13 20:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0012_auto_20180413_2126'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveSnake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.SnakeVersion')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='snake',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='snake',
            name='user',
        ),
        migrations.RemoveField(
            model_name='snake',
            name='version',
        ),
        migrations.DeleteModel(
            name='Snake',
        ),
    ]
