# Generated by Django 2.0.4 on 2018-04-14 22:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0013_auto_20180413_2204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activesnake',
            name='id',
        ),
        migrations.AlterField(
            model_name='activesnake',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='snakeversion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='snakeversion',
            unique_together={('user', 'version')},
        ),
    ]
