# Generated by Django 2.0.4 on 2018-04-25 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0017_auto_20180424_2147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snakegame',
            name='score',
        ),
        migrations.AddField(
            model_name='snakegame',
            name='end_frame',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='snakegame',
            name='final_mass',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='snakegame',
            name='killer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games_won', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='snakegame',
            name='start_frame',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servercommand',
            name='command',
            field=models.CharField(choices=[('kill', 'kill')], max_length=255),
        ),
        migrations.AlterField(
            model_name='servercommand',
            name='dt_processed',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='servercommand',
            name='result',
            field=models.NullBooleanField(editable=False),
        ),
        migrations.AlterField(
            model_name='servercommand',
            name='result_msg',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
    ]
