# Generated by Django 2.0.4 on 2018-04-28 21:22

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20180428_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='viewer_key',
            field=models.BigIntegerField(default=None, unique=True),
        ),
    ]
