# Generated by Django 2.0.4 on 2018-04-29 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_userprofile_viewer_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='snakeversion',
            name='server_error_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
