# Generated by Django 2.0.4 on 2018-05-01 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_snakeversion_server_error_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snakeversion',
            name='prev_version',
        ),
        migrations.AddField(
            model_name='snakeversion',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.SnakeVersion'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='active_snake',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.SnakeVersion'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='viewer_key',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.DeleteModel(
            name='ActiveSnake',
        ),
    ]
