# Generated by Django 2.0.4 on 2018-05-02 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('core', '0022_auto_20180501_1134'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveStats',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('last_update_frame', models.IntegerField(blank=True, null=True)),
                ('mass', models.FloatField(blank=True, null=True)),
                ('natural_food_consumed', models.FloatField(blank=True, null=True)),
                ('carrison_food_consumed', models.FloatField(blank=True, null=True)),
                ('hunted_food_consumed', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='snakegame',
            name='carrison_food_consumed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='snakegame',
            name='hunted_food_consumed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='snakegame',
            name='natural_food_consumed',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
