# Generated by Django 2.0.4 on 2018-05-08 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_apikey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='comment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='key',
            field=models.CharField(default='cd7bb8dd-9e7d-4b91-8950-807b10545b7a', max_length=100),
        ),
    ]
