# Generated by Django 2.0.1 on 2018-01-10 21:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    operations = [
        migrations.RunSQL(
            """
            DROP VIEW IF EXISTS highscore_highscore;
         
            CREATE VIEW highscore_highscore AS 
              SELECT (SELECT COUNT(0) FROM core_snakegame i WHERE i.score >= a.score) as id,
                     u.username, 
                     a.score 
               FROM core_snakegame a INNER JOIN auth_user u ON a.user_id = u.id
               ORDER BY score DESC;
            """
        ),        
    ]
