# Generated by Django 2.0.3 on 2018-03-30 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('highscore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Highscore',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150)),
                ('score', models.IntegerField()),
            ],
            options={
                'db_table': 'highscore_highscore',
                'managed': False,
            },
        ),
    ]
